### ISSUE TITLE
Unable to load magic1.dll manually in windows

### ISSUE THREAD

**Issue by patachi** [hey-red/Mime#10]
it would be great if you update this  :>
ty in advance .

Errors : 
1. Unable to load DLL 'libmagic1': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

2. An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

Stack Trace :
   at HeyRed.Mime.MagicNative.magic_open(MagicOpenFlags flags)
   at HeyRed.Mime.Magic..ctor(MagicOpenFlags flags, String dbPath)
   at HeyRed.Mime.MimeGuesser.GuessMimeType(Byte[] buffer, Int32 size)
.....

**Comment by hey-red** [comment]
This means that you are trying to use x86 dll in x64 proj or vice versa.
If you need x64 dll, then you can get it [here](https://github.com/nscaife/file-windows/releases) Later, I build an assembly for Windows.

**Comment by patachi** [comment]
hmm
I tried both x86 & x64 mode still Unable to load DLL 
and the same error :
An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B))

**Comment by hey-red** [comment]
@patachi I'm updated the package with windows support (included x64 dll). Now you do not need to install the DLL manually.

**Comment by patachi** [comment]
ohh thank you ^_^

welp i create new classic win form project and added Mime with NuGet (Update Saturday, April 8, 2017 (4/8/2017)) and write a simple code like


        public string TryToGetFileExtension(byte[] fileBuff)
        {
            var fileExtension = "";
            try
            {
                //HeyRed.Mime.MimeGuesser.MagicFilePath = @"magic.mgc";

                var tmpLength = (fileBuff.Length > 512 ? 512 : fileBuff.Length);
                var tmpBuff = new byte[tmpLength];
                Array.Copy(fileBuff, tmpBuff, tmpLength);
                fileExtension = HeyRed.Mime.MimeGuesser.GuessExtension(tmpBuff, tmpBuff.Length);

                tmpBuff = null;
            }
            catch (Exception exp)
            {
                System.Diagnostics.Debug.WriteLine(exp.Message);
            }

            return fileExtension;
        }


and still i got this error : 
Unable to load DLL 'libmagic-1': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

**Comment by hey-red** [comment]
Hmm, it's very strange. Which windows version you are using? 32 or 64 bit?
Off course I should've be test it with full .net framework.

**Comment by patachi** [comment]
win 10 x64

**Comment by hey-red** [comment]
Ok, I have same system. You can create .net core console project and test your example?
I'm busy right now and answer later.

**Comment by hey-red** [comment]
@patachi It's seems like i'm solve that problem. Update package and you will need to set platform x64 in your application.

**Comment by patachi** [comment]
yup it works fine
thanks @hey-red

**Comment by sacerdotu** [comment]
@hey-red Last version (2.3.0) not working for AnyCPU platform.
Current configuration:
Win 10, x64
VS 2017, Platform: AnyCPU

**Comment by hey-red** [comment]
@sacerdotu change platform to x64.

**Comment by sacerdotu** [comment]
@hey-red  But I need anycpu :) If I change to x64 it will work for sure.

**Comment by sacerdotu** [comment]
@hey-red This is an issue that should be fixed

**Comment by hey-red** [comment]
Currently there is no x86 support. Maybe later i'm trying to build 32-bit libmagic, and АnyCPU will be works by default.

**Comment by sacerdotu** [comment]
Perfect. Waiting for the new version!

**Comment by sacerdotu** [comment]
@hey-red Any news?

**Comment by hey-red** [comment]
I did not work with azure, but if your app is self contained(contains all dependencies in working dir), then you need to copy libmagic and and other files from win runtime into directory that contains your app.

**Comment by himadrinath** [comment]
@hey-red  i did now i am getting another error

> An unhandled exception occurred while processing the request.

BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

>

**Comment by hey-red** [comment]
Your VM under linux or windows?

**Comment by himadrinath** [comment]
@hey-red windows

**Comment by himadrinath** [comment]
@hey-red i found this https://github.com/aspnet/KestrelHttpServer/issues/1625#issuecomment-293473036

**Comment by hey-red** [comment]
Yep, its seems like app run in x86 mode. Also, by default azure VM uses x64 windows?
Change target platform to x64 and publish your app again.

**Comment by himadrinath** [comment]
@hey-red working on it. lets see what happen. i will inform you the result

**Comment by himadrinath** [comment]
@hey-red i changed the runtime to <RuntimeIdentifier>win-x64</RuntimeIdentifier> and deploy to azure now its working fine. thanks for your help
