### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by JornEngelbart** [hey-red/Mime#11]
It would be nice if macOS support could be added, then we would be able to use it in our dev environment as well. I tried to clone the repo and add the .dylib and csproj changes myself, but I couldn't get it running with the same sort of configuration as for Windows and Linux. It couldn't find the lib when it was place in the runtimes/osx.10.12-x64/native/ folder, with the same csproj config as for the other platforms. When it was placed in the root folder everything was fine (but of course not the way to go).
I could provide the .dylib if you need it.

**Comment by hey-red** [comment]
You trying to run tests?

**Comment by JornEngelbart** [comment]
I actually did not. I tried to directly use it in my project. But it does work when running the tests except for one. The latest version of libmagic I could get my hands on for mac is 5.26 and the tests require 5.30. Any specific reason for this? If not I could create a pull request.

**Comment by hey-red** [comment]
Oh, ok. You can create PR, also see [this line](https://github.com/hey-red/Mime/blob/master/test/MimeTests/MimeTests.csproj#L34). 
It's required to copying libs from runtimes directory into tests output.
>The latest version of libmagic I could get my hands on for mac is 5.26 and the tests require 5.30. Any specific reason for this?

It's not strongly required, but needed for correct work across all platforms. Maybe take it from [brew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/libmagic.rb)? It' not hard to build it from source, like brew.

**Comment by hey-red** [comment]
Nuget package has been updated.

**Comment by JornEngelbart** [comment]
Great, thanks!
