### ISSUE TITLE
Cannot run it on Linux

### ISSUE THREAD

**Issue by krlm** [hey-red/Mime#13]
Hi, 

I cannot use ver 2.2.0 on Linux, neither WSL (Ubuntu 16.04) nor official MS docker, both with dotnet cli 1.0.4 aren't working. 

Exception from WSL (Ubuntu 16.04): 
```
Unhandled Exception: HeyRed.Mime.MagicException: Could not find any valid magic files!
   at HeyRed.Mime.Magic..ctor(MagicOpenFlags flags, String dbPath)
   at HeyRed.Mime.MimeGuesser.GuessMimeType(Byte[] buffer, Int32 size)
   at HeyRed.Mime.MimeGuesser.GuessFileType(Byte[] buffer, Int32 size)
   at test.Program.Main(String[] args) in /home/test/Program.cs:line 11
```
Exception from docker:
```
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'libmagic-1': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at HeyRed.Mime.MagicNative.magic_open(MagicOpenFlags flags)
   at HeyRed.Mime.Magic..ctor(MagicOpenFlags flags, String dbPath)
   at HeyRed.Mime.MimeGuesser.GuessMimeType(Byte[] buffer, Int32 size)
   at HeyRed.Mime.MimeGuesser.GuessFileType(Byte[] buffer, Int32 size)
   at test.Program.Main(String[] args) in /home/test/Program.cs:line 11
```
Program code: 
```csharp
using System;
using HeyRed.Mime;

namespace Test
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");			
            Console.WriteLine(MimeGuesser.GuessFileType(new byte[] { 0xFF, 0xD8, 0xFF  }));
        }
    }
}
```

**Comment by hey-red** [comment]
For first error try to set magic file path :
MimeGuesser.MagicFilePath = "/path/to/magic/magic.mgc";
but it's very strange errors. 
I'm tested that library on my server(16.04) and it worked fine. 
I can investigate this later.

**Comment by krlm** [comment]
Are you sure you don't have `libmagic`  in your `/lib` or `/usr/lib` folders (or sub `x86_64-linux-gnu`)? It works when I manually `apt-get install` `libmagic` package to the system.

**Comment by hey-red** [comment]
Of course, because nuget package is distributed with libmagic already. Their names do not match and the version of the package is usually higher(builded from the git).

**Comment by krlm** [comment]
I know that libmagic is distributed with nuget package but it doesn't seem to work on systems which have not installed libmagic 'natively` (in `/lib/*` or `/usr/lib` dir.). That's why I've asked that you're sure you don't have that lib in system dirs. I've added version for Debian RID here: https://github.com/krlm/Mime/tree/feature/add-debian-native-libmagic but didn't have a chance to check it yet.

**Comment by krlm** [comment]
With that PR I've unified behaviour on Ubuntu  and Debian, currently on both I've the same message:
```
Unhandled Exception: HeyRed.Mime.MagicException: Could not find any valid magic files!
```
when `libmagic1` isn't installed as a system package (i.e. `apt-get remove libmagic1` or run in isolated dotnet docker). I've investigated it further and this is how default lookup of `magic.mgc` looks like: 
```
stat("/home/krlm/.magic.mgc", 0x7fffe3d08a90) = -1 ENOENT (No such file or directory)
stat("/home/krlm/.magic", 0x7fffe3d08a90) = -1 ENOENT (No such file or directory)
access("/usr/local/share/misc/magic.mime.mgc", R_OK) = -1 ENOENT (No such file or directory)
open("/usr/local/share/misc/magic.mgc", O_RDONLY) = -1 ENOENT (No such file or directory)
stat("/usr/local/share/misc/magic", 0x7fffe3d08a70) = -1 ENOENT (No such file or directory)
open("/usr/local/share/misc/magic", O_RDONLY) = -1 ENOENT (No such file or directory)
```
Here's the code responsible for default lookup: https://github.com/file/file/blob/FILE5_30/src/magic.c#L175. So, only on windows locations relative to the lib are checked. 

I don't have solution for that yet - other than installing libmagic in the system, or copying `magic.mgc` into one of those locations. However, it should be possible to obtain a location of Mime.dll and then use it to build fixed path of `magic.mgc`. Other idea might be coping `magic.mgc` to the build output path.

**Comment by hey-red** [comment]
I'm created little hack based on nuget package path. Ugly, but it should work.
https://github.com/hey-red/Mime/commit/e67e4f4db06fa93fa1038e2b2ed8c9b4caac49b1#diff-7cbaa6591ca9387c8f9df59ea78248dcR12
Also, @JornEngelbart 
If OS X has same path to nuget packages, we can use it too. 
In any case, we can choose better option.

**Comment by JornEngelbart** [comment]
@hey-red Yes, it seems to be the same path, not explicitly tested though.

Would it be better to just copy the magic.mgc file to the build folder and use it from there (possibly conditioned on Linux)? Relying on the nuget folder seems very dirty to me

**Comment by hey-red** [comment]
@JornEngelbart That method has one problem:
If you use Mime in **project1**, all ok.
When using **project1** in **project2**, the files are not copied.

**Comment by JornEngelbart** [comment]
This is a MSBuild bug right? You'd hope there would be a better way 🙃

**Comment by krlm** [comment]
@JornEngelbart - that was a MSBuild bug - don't know if still valid, tough.
@hey-red - yes, I was thinking about sth. similar, like 
```
var location = typeof(MagicUtils).GetTypeInfo()
                                                 .Assembly
                                                 .Location;
```
but location isn't available in .netstandard 1.3
Anyway, it's working for me now, so this issue can be closed. Thanks for help.

**Comment by Felsoon** [comment]
Regarding to this issue, has this been reverted?
https://github.com/hey-red/Mime/commit/e67e4f4db06fa93fa1038e2b2ed8c9b4caac49b1

Beacues I don`t see this changes on the master branch, and today I got this exact error and was wondering, why does this still occure, but i turns out, those changes are not present on the master branch
