### ISSUE TITLE
Add Additional Info

### ISSUE THREAD

**Issue by Dyedan** [hey-red/Mime#16]
the linux file command returns more information about the file type, it's encoding, endians, sometimes even a description. It would be nice to have that data available too, assuming that kind of data is present in the magic.mgc file.

Also, I just wanted to say, thank you so much for making this project, after a few days of banging my head against the wall I found it and it looks promising!

**Comment by hey-red** [comment]
You can use Magic class directly(MimeGuesser it's just static facade for this class).
For example:
```C#
using (var magic = new Magic(
        MagicOpenFlags.MAGIC_MIME_TYPE |
        MagicOpenFlags.MAGIC_MIME_ENCODING, 
        null))
 {
        Console.WriteLine(magic.Read("/path/to/file"));
 }
```
see [magic flags](https://github.com/hey-red/Mime/blob/master/src/Mime/MagicOpenFlags.cs) for more(also, maybe in 5.30 added more flags).

**Comment by Dyedan** [comment]
Silly me, I didn't notice that. I think this should be added to the examples in the README.

**Comment by hey-red** [comment]
PR are welcome 😃
