### ISSUE TITLE
Port to .net core 2.0

### ISSUE THREAD

**Issue by Bakanych** [hey-red/Mime#18]
Hi, any plans related to subj?

**Comment by hey-red** [comment]
Yes, but when he will be released. 
Ofcourse maybe i'm make prerelease package with that target.

**Comment by Bakanych** [comment]
@hey-red it will be super-nice as i'm developing the project using the latest .net core preview.
Спасибо :)

**Comment by hey-red** [comment]
Хорошо. Постараюсь сегодня вечером опакетить. 
Судя по всему еще желательно поставить превью студии для этого.

**Comment by hey-red** [comment]
@Bakanych а вообще можно же использовать и текущую версию в 2.0

**Comment by hey-red** [comment]
At this moment the Mime use NETStandard 1.3 and works with .NET Core 2.0(NET Standard 2.0).
