### ISSUE TITLE
Differece in  MimeType  detection

### ISSUE THREAD

**Issue by Kkomkov** [hey-red/Mime#19]
There is difference in MimeType detection for  file and  byte array for the same file 

 FileStream fs = new FileStream(filePath, FileMode.Open, FileAccess.Read);
 byte[] ImageData = new byte[fs.Length];
 fs.Read(ImageData, 0, System.Convert.ToInt32(fs.Length));

  **var res = MimeGuesser.GuessFileType(ImageData);
   var res2 = MimeGuesser.GuessFileType(filePath);**
check for *.docx files.

**Comment by hey-red** [comment]
Try to increase buffer size(default 512). I think default size too small for docx detection.
For example:
`MimeGuesser.GuessFileType(ImageData, ImageData.Length);`

**Comment by Kkomkov** [comment]
Thank you . I'll try.

**Comment by Kkomkov** [comment]
Grate it works. Thank you.

**Comment by hey-red** [comment]
@Kkomkov Now in 3.0 it default behavior.
You should use:
`MimeGuesser.GuessFileType(ImageData);`

**Comment by Kkomkov** [comment]
Grate.Thank you .
