### ISSUE TITLE
htm/html detected as text/plain

### ISSUE THREAD

**Issue by BinariaDigital** [hey-red/Mime#21]
Hi,
when i try MimeGuesser on htm, html files I get "text/plain". If I execute file on command line it correctly reports them as "text/html".
(i have used attached file for testing)
[MIME type guesser.zip](https://github.com/hey-red/Mime/files/1591104/MIME.type.guesser.zip)

I have pointed MagicFilePath to the very same magic.mgc file command uses.
Also, I have tested with the one from https://launchpad.net/ubuntu/artful/amd64/libmagic-mgc/1:5.29-3, same results: text/plain
In linux, if I delete magic.mgc then file also reports the test file as "text/plain", but if is able to find the magic.mgc file then its properly detected as "text/html"

Thanks.

**Comment by hey-red** [comment]
Fixed 34413d5
The problem is that by default guesser don't check encoding.

**Comment by BinariaDigital** [comment]
var magic = new Magic(MagicOpenFlags.MAGIC_ERROR |
                                  MagicOpenFlags.MAGIC_MIME_TYPE |
                                  MagicOpenFlags.MAGIC_NO_CHECK_COMPRESS |
                                  MagicOpenFlags.MAGIC_NO_CHECK_ELF |
                                  MagicOpenFlags.MAGIC_NO_CHECK_APPTYPE);
worked as expected.
Thanks.

**Comment by hey-red** [comment]
Nuget package has been updated.
