### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by promikhail** [hey-red/Mime#22]
var mimeType = MimeGuesser.GuessMimeType(filePath);

On server throwns exception:
`Cannot stat 'C:\inetpub\wwwroot\StudentFiles\Portfolio\5179\2\???????? C# 6.0.pdf' (No such file or directory)`

But file exists, and it checked before. filePath have right path with Cyrillic chars. If rename file to with only english chars it works normally.

On dev computer this exception not thrown, it happen only on prod server. Why?

**Comment by promikhail** [comment]
Temporarily solved like this:
`var mimeType = "";
            using (var file = File.Open(filePath, FileMode.Open, FileAccess.Read))
            {
                mimeType = MimeGuesser.GuessMimeType(file);
            }`

**Comment by hey-red** [comment]
The dev PC on linux/mac? 
I don't know how to resolve this, because libmagic on Windows can handle only ASCII characters.
Anyway we can use these overloads:
```
GuessMimeType(byte[] buffer)
GuessMimeType(Stream stream)
```

**Comment by promikhail** [comment]
Dev PC:
- Windows 10 Pro
- Intel Core i5-6600
- NTFS
Prod:
- Windows Server 2016 Standard
- Intel Xeon E5-2650
- NTFS

If libmagic handle only ASCII chars, it is strange that it works on my Dev PC.
Thanks!
