### ISSUE TITLE
[htm, html, xml] Detected as text/plain

### ISSUE THREAD

**Issue by plachor** [hey-red/Mime#24]
Hi @hey-red, I have encountered an issue-or-unwanted behavior, when validating files of types **htm**, **html** and **xml**. Everything works fine till we work with files using line endings appropriate for host system.

But once we try to check on Linux  **htm** file  with Windows line endings (CR LF) it detects **text/plain**. Same with Unix line endings (LF) checked against Windows host.

Is there some **magic**  flag to magic tool that will help me positively identify files without converting line endings.

**Comment by hey-red** [comment]
I can't reproduce this. 
Can you provide test file(with unix le)?

**Comment by plachor** [comment]
Will trying reproduce I found issue on my side .. sorry @hey-red and thnx for quick response.
