### ISSUE TITLE
file type is detected Unknown

### ISSUE THREAD

**Issue by RezaRahmati** [hey-red/Mime#29]
Hello

We have an issue we can't figure it out, you might be able to help.

On our local dev machines everything is fine, but when we deploy to qa or uat or prod, file types are detected as 'unknown', we have no clue why it's happening. is there any log somewhere to take a look

we are using it with .net core 2.1.2
p.s we tried with both 3.0.1 and 3.0.2 and result is the same

**Comment by hey-red** [comment]
Without any exceptions? Prod server running on linux/windows?

**Comment by RezaRahmati** [comment]
Vow, thanks for fast response, 
No exception as far as I know, everything is on windows hosted on AWS

**Comment by hey-red** [comment]
I guess no. All possible exceptions should be catch by runtime.

**Comment by RezaRahmati** [comment]
I found what is the exception

```
System.DllNotFoundException: Unable to load DLL 'libmagic-1' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at HeyRed.Mime.MagicNative.magic_open(MagicOpenFlags flags)
   at HeyRed.Mime.Magic..ctor(MagicOpenFlags flags, String dbPath)
   at HeyRed.Mime.MimeGuesser.GuessMimeType(Byte[] buffer)
   at HeyRed.Mime.MimeGuesser.GuessFileType(Byte[] buffer)
```

**Comment by hey-red** [comment]
If you are use SCD, then drop [these files](https://github.com/hey-red/Mime/tree/master/src/Mime/runtimes/win-x64/native) into directory with your app.
And set path to magic db `MimeGuesser.MagicFilePath = "/path/to/magic.mgc";` 
We can get magic.mgc [here](https://github.com/hey-red/Mime/tree/master/src/Mime/content)

But if you are publish app through visual studio you need only set path.

**Comment by RezaRahmati** [comment]
Yes

**Comment by RezaRahmati** [comment]
I checked the qa env, files were exists in a this folder `runtimes\win-x64\native`
I set the magicPath to `runtimes\win-x64\native\magic.mgc` and `\runtimes\win-x64\native\magic.mgc` and `runtimes/win-x64/native/magic.mgc` and `/runtimes/win-x64/native/magic.mgc`  and still same error.

Then I copied all of that 3 files (2 dlls and magic.mgc) beside other dlls in the root, and still same error

**Comment by hey-red** [comment]
I created test app, then just publish it into local directory(via VS) and it works

![ex](https://user-images.githubusercontent.com/1738743/50247731-c80bf180-03e9-11e9-8cfe-3b5895b8979b.png)
