### ISSUE TITLE
All SVG are identified as text/svg instead of text/svg+xml

### ISSUE THREAD

**Issue by minuz** [hey-red/Mime#30]
Hi, I've been using this library for security check on file upload.

As a recommended security check, we shouldn't allow upload of files where the declared mimeType (.svg) does not match the detected mime type. 
However, when trying a few file types, we get some misleading results.

`.svg` has been identified as `image/svg` and all svg files generated from several applications generates as 'image/svg+xml'

Some `.xmlx, .docx, .pptx` are identified as `application/zip`
Can you have a look and/or point if I'm doing something wrong? 
Essentially just using like the following
```csharp
        internal string GetMimeType(byte[] buffer)
        {
            return HeyRed.Mime.MimeGuesser.GuessMimeType(buffer);
        }
```

**Comment by hey-red** [comment]
I think all problems related to libmagic/magic.mgc. Maybe updated package solve it.
