### ISSUE TITLE
Update documentation to mention that magic_open isn't thread safe (new Magic())

### ISSUE THREAD

**Issue by rwasef1830** [hey-red/Mime#34]
Hello,
Using this library in a parallel loop (creating new Magic() inside the loop) was causing my app to crash randomly with a heap corruption exception code.

The documentation should be updated to mention that you cannot create new Magic instances simultaneously (or alternatively add a lock inside the constructor) to prevent random crashes for people consuming the library.

Once the separate magic instances are serially constructed, they can be used concurrently with no ill effects.

**Comment by hey-red** [comment]
How to reproduce it?

I'm trying to create threads without pool like this:

```C#
using System;
using System.IO;
using System.Threading;

using HeyRed.Mime;

namespace TestApp
{
    class Program
    {
        static void Main(string[] args)
        {
            var files = Directory.GetFiles("/path/to/files");

            for (int i = 0; i < 500; i++)
            {
                Thread t = new Thread(() => 
                {
                    string filePath = files[i];

                    var magic = new Magic(MagicOpenFlags.MAGIC_MIME_TYPE);

                    string mimeType = magic.Read(filePath);

                    Console.WriteLine($"File: {filePath}: {mimeType}");
                });

                t.Start();
            }
        }
    }
}
```

But it works as expected.
Btw if we need lock inside constructor, then we need it around all methods that works with pointer.

**Comment by rwasef1830** [comment]
It happened to me in Parallel.ForEach on an array and creating a Magic instance inside the body lambda.
It would randomly crash with Heap corruption.

**Comment by hey-red** [comment]
@rwasef1830 Host is Linux?

**Comment by rwasef1830** [comment]
No, I was running my app on Windows 10. Once I locked around Magic instantiation, I could use the multiple instances simultaneously without problem.

**Comment by rwasef1830** [comment]
Here's the commit where I fixed it: https://github.com/rwasef1830/funkygrep/commit/6d62c3cbabd9a64eb35fbf5093f6e1afe9e04aa4

**Comment by hey-red** [comment]
Hmm, when I'm share single instance of Magic I got same issue, but if I create new instance in parallel loop it's work as expected.
So yes, it's covered in [remarks ](https://github.com/hey-red/Mime#remarks)
I think we should leave it as it is, because Magic is low level abstraction and most users not needed to go deeper than MimeGuesser. 
But I'm should hightlight it in readme anyway.
Thanks for report 👍

**Comment by hey-red** [comment]
Also, I'm see golang implementation and its uses mutex for all operations
https://github.com/rakyll/magicmime/blob/master/magicmime.go#L181
🤔

**Comment by rwasef1830** [comment]
@hey-red the problem is that magic_open called in the constructor is not safe, so even the constructor needs to be locked. You can add a lock inside around magic_open, because libmagic changes shared memory on library initialization.

**Comment by hey-red** [comment]
@rwasef1830 Okay, seems like reasonable. 
But should I use static object? Or instance based lock is fine?

**Comment by rwasef1830** [comment]
Must be static locking object. @hey-red

**Comment by hey-red** [comment]
Done 7acf3f1

**Comment by rwasef1830** [comment]
👍
