### ISSUE TITLE
missing alpine linux x64 support

### ISSUE THREAD

**Issue by hgy59** [hey-red/Mime#35]
dotnet core 3.1 supports alpine linux but mime does not.

when running a dotnet core 3.1 app with this mime library under docker with `mcr.microsoft.com/dotnet/core/runtime-deps:3.1-alpine` and installed libmagic 5.38 - I get an app crash (segmentation fault).
But when running with the debian based image with `mcr.microsoft.com/dotnet/core/runtime-deps:3.1` the app runs successfully (libmagic is installed out of the box).
So I suppose the bundled libmagic-1.so is not compatible with libmagic 5.38 installed in alpine linux.

Appreciate any hint how to get mime running on alpine linux based docker images.

**Comment by hey-red** [comment]
e205d42
