### ISSUE TITLE
Unable to find libmagic-1 on Ubuntu 20.04

### ISSUE THREAD

**Issue by ntsim** [hey-red/Mime#36]
When running some Azure Function code that uses this dependency on Ubuntu 20.04, it seems that I get the following:

> Unhandled exception. System.DllNotFoundException: Unable to load shared library 'libmagic-1' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibmagic-1: cannot open shared object file: No such file or directory

I'm using Azure's `func` CLI tool to run the code, but I'm not entirely sure running this code via the `dotnet` CLI would yield much better results. Seems like it boils down to [MAGIC_LIB_PATH](https://github.com/hey-red/Mime/blob/6d16754403fb142968c16052eb9418bc22b54914/src/Mime/MagicNative.cs#L8) expecting libmagic to be referenced as `libmagic-1`.

Running `apt install libmagic-dev` installs `libmagic` to: `/usr/lib/x86_64-linux-gnu/libmagic.so`. I would expect there to be a inbuilt way for this library to more robustly detect where `libmagic` is or to be able to change `MAGIC_LIB_PATH` ourselves.

### Workaround

Thankfully, there's a workaround. You can create symlinks to the proper `libmagic` like so:

```
cd /usr/lib/x86_64-linux-gnu/
sudo ln -s libmagic.so.1.0.0 libmagic-1.so
sudo ln -s libmagic.so.1.0.0 libmagic-1.so.1
```

**Comment by hey-red** [comment]
Yes, it should be using Environment.SetEnvironmentVariable with LD_LIBRARY_PATH on *nix to detect installed libmagic,
but nuget package is already contains libmagic with required version. See https://github.com/hey-red/Mime/tree/master/src/Mime/runtimes
When you publish your app(via Visual Studio), **libmagic(.dll or .so)** and **magic.mgc** copied according to your target runtime. 
So there is no need to maintain host version of libmagic.

**Comment by ntsim** [comment]
Sorry, I don't use Visual Studio (and don't have a lot of experience with C#) so I don't really know how publishing the app through it would make a difference on Linux?

When I start the app, it seems like the `libmagic-1.so` and `magic.mgc` files are outputted to my project's `bin/output` directory like so:

![image](https://user-images.githubusercontent.com/9917868/92971515-7e462300-f478-11ea-9d51-d11217f6dd1c.png)

Unfortunately it doesn't seem like Mime can detect it (as per the issue). It seems like you're suggesting that it should automatically work out of the box though?

Thanks for the tip, about `LD_LIBRARY_PATH`, although it's probably not the best solution for this problem.

**Comment by hey-red** [comment]
Yes, it should be works out of box and I think your runtime is fine.
If you development app on local machine thats what you need is only `dotnet run` inside your app directory that contains .csproj

But when you deploy to production host we need to publish app with required runtimes.
For example:
Navigate your project directory(that contains .csproj): `cd /home/sources/path/to/project`
then

`dotnet publish -p:PublishProfile=FolderProfile --runtime linux-x64`

then inside bin/../../linux-x64/publish dir you can see all files for current runtime
run it with `dotnet YourApp.dll`

**Comment by ntsim** [comment]
Cool, thanks for clarifying! :smile: 

Unfortunately I'm not using `dotnet` to run this code as my project is using it via an Azure Function. Locally, I'm using `func` (see [Azure Function Core Tools](https://github.com/Azure/azure-functions-core-tools)) to run the code so it's unclear what it's doing in comparison to using `dotnet`. I've just spoken with a teammate that had successfully used the code via `dotnet` in the past, so it does look like an issue with how `func` makes the runtime dependencies discoverable.

I guess this problem is more with Azure Function Core Tools, unless there's something else that can be done from Mime's perspective?

**Comment by ntsim** [comment]
For anyone interested in what I've ended up doing. You can add the following to your function project's csproj to get your build to copy the native lib files to the correct output directory:

```xml
<!-- Copy files that function build strips out that should normally be included  -->
<Target Name="CopyFilesAfterBuild" AfterTargets="_GenerateFunctionsPostBuild">
  <ItemGroup>
    <NativeLibs Include="$(OutDir)runtimes\**\libmagic-1.so" />
    <NativeLibs Include="$(OutDir)runtimes\**\libmagic-1.dylib" />
    <NativeLibs Include="$(OutDir)runtimes\**\libmagic-1.dll" />
    <NativeLibs Include="$(OutDir)runtimes\**\libgnurx-0.dll" />
  </ItemGroup>
  <Copy SourceFiles="@(NativeLibs)" DestinationFolder="$(OutDir)bin\runtimes\%(RecursiveDir)" />
  <!-- Doesn't matter which runtime the magic.mgc file comes from, they're all the same -->
  <Copy SourceFiles="$(OutDir)runtimes\win-x64\native\magic.mgc" DestinationFolder="$(OutDir)bin" />
</Target>
```

Upon starting your function using `func start`, this should no longer be a problem.
