### ISSUE TITLE
Different results using filePath vs stream input

### ISSUE THREAD

**Issue by jrmitch120** [hey-red/Mime#39]
First I created an empty .xlsx document using Excel.  Then I ran it through `MimeGuesser.GuessMimeType`, once with the filePath overload and once with the stream overload.

The filePath overload produced the correct result, while the stream overload produced an `application/zip` result.  

![image](https://user-images.githubusercontent.com/1315635/108572671-6b156a00-72d8-11eb-8f5e-bb381f353435.png)

**Comment by jrmitch120** [comment]
It looks like this is a know bug with libmagic:

https://manpages.debian.org/experimental/libmagic-dev/libmagic.3.en.html

> BUGS
The results from magic_buffer() and magic_file() where the buffer and the file contain the same data can produce different results, because in the magic_file() case, the program can lseek(2) and stat(2) the file descriptor.

**Comment by hey-red** [comment]
By default the Stream overload have limit in bytes(under the hood it just call magic_buffer) https://github.com/hey-red/Mime/blob/master/src/Mime/MimeGuesser.cs#L72
So, maybe it produce problems for some types. You can try to use https://github.com/hey-red/Mime/blob/master/src/Mime/MimeGuesser.cs#L48 it can be works.
I'l try to update libmagic binaries in next few days.
