### ISSUE TITLE
Got error with visual studio 2015

### ISSUE THREAD

**Issue by DjSiwach** [hey-red/Mime#40]
Hi,

I want use MIME lib in my project to find the file extension but when I am going to install by visual studio 2015 after install I have got following error. please help me out.

 error  : Invalid static method invocation syntax: "[System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux))". The type "System.Runtime.InteropServices.RuntimeInformation" is either not available for execution in an MSBuild property function or could not be found

![image](https://user-images.githubusercontent.com/7755950/112449281-3aae6900-8d79-11eb-994b-4f64dbb8211b.png)

**Comment by DjSiwach** [comment]
@hey-red please help me out.

**Comment by hey-red** [comment]
You can't upgrade VS? Currently I don't have time to fix props for old VS. 
Maybe you can use https://github.com/ied206/Joveler.FileMagician or another similar project instead of Mime.

**Comment by DjSiwach** [comment]
Thanks @hey-red
