### ISSUE TITLE
libmagic dependency mismatch on MacOS Monterey (5.41) 

### ISSUE THREAD

**Issue by luke-h1** [hey-red/Mime#43]
Hey, 
Currently, I am getting the following exception in my application (c# Azure function) when using Mime due to a mismatch of dependencies (I think): 

Exception:
```bash
Mime: File 5.41 supports only version 16 magic files. `/bin/output/bin/magic.mgc' is version 14.
```

This is what I ran when installing libmagic: 
```bash
brew install libmagic
brew link libmagic
env ARCHFLAGS="-arch x86_64" gem install ruby-filemagic -- --with-magic-include=/usr/local/include --with-magic-lib=/usr/local/lib/
```

This happened on a 64bit Intel Mac running Monterey. The Azure function is running on the following Mime version: `3.0.0` 

Have you come across this issue before and if so is there a solution?

**Comment by hey-red** [comment]
Seems like you are install latest version of libmagic from homebrew(but why?). 
Do you need a fresh version of database file. It's can be taken from here:

`https://github.com/hey-red/Mime/blob/master/src/Mime/content/magic.mgc`

or maybe inside installation directory 

`/usr/local/include`

then set path to this file
MimeGuesser.MagicFilePath = "/path/to/magic.mgc";

**Comment by luke-h1** [comment]
Hi, it turns out the solution was to simply install `ruby-libmagic` from https://rubygems.org/gems/libmagic. Once I installed this, I no longer get the exception: 
```
Mime: File 5.41 supports only version 16 magic files. `/bin/output/bin/magic.mgc' is version 14.
```

Thanks for the help!
