### ISSUE TITLE
Update file to 5.44

### ISSUE THREAD

**Issue by JohnHBrock** [hey-red/Mime#49]
Any objections to upgrading to 5.44? I'm generally seeing more useful, specific, and detailed results from 5.44 compared to 5.41.

**Comment by hey-red** [comment]
I just don't have enough time for it. PR are welcome.
Windows build is most problematic part of this(source patching and other things).

I already have some poorly writed scripts to do this. Maybe it help.
https://github.com/hey-red/Libmagic-Build

**Comment by andreas-eriksson** [comment]
There has now also been a release of 5.45 https://github.com/file/file/releases/tag/FILE5_45

**Comment by jspraul** [comment]
Here's an example building/grabbing near-latest libmagic: [Build platform-specific wheels containing libmagic](https://github.com/ahupp/python-magic/pull/294)

It grabs the Windows releases here: https://github.com/julian-r/file-windows/releases

**Comment by GoNextGroup** [comment]
Hope, you'll find time for update. We do need your library, there are no alternatives.(((

**Comment by hey-red** [comment]
Updated to 5.45 https://github.com/hey-red/Mime/commit/ff64091cdacc86a5fe320f0cdb1fd7494ae62eee
