### ISSUE TITLE
Does not pick up Parquet files

### ISSUE THREAD

**Issue by jchristn** [hey-red/Mime#50]
Hi, thanks for this awesome library!  I noticed it does not detect parquet files.  I understand there is no standard MIME type for it, but perhaps the extension returned from ```GuessExtension``` could be ```parquet```?  

Is there a general set of guidelines for how to handle content-types that aren't known or documented?

**Comment by hgy59** [comment]
@jchristn this mime guesser library is just a wrapper for libmagic.

You find the source code of `libmagic` in https://github.com/file/file and more information on https://www.darwinsys.com/file/
You could define your own mimetypes and find all existing definitions in the [MagDir](https://github.com/file/file/tree/master/magic/Magdir) of this project.
When you create a custom `magic.mgc` file, it will work with this mime guesser library under .NET.

**Comment by hey-red** [comment]
Apache parquet already supported by libmagic, but yes - no standard mime type.

You can use Magic class to detect it and return right extension:

```C#
using HeyRed.Mime;

using var magic = new Magic(MagicOpenFlags.MAGIC_NONE);
string result = magic.Read("/path/to/file.parquet"); // returns "Apache Parquet"
```
