### ISSUE TITLE
Manually install libmagic

### ISSUE THREAD

**Issue by monotore** [hey-red/Mime#9]
How do I manually install libmagic for Windows?

**Comment by hey-red** [comment]
If you use x64 Windows:
1). Download dll's from that repo https://github.com/pidydx/libmagicwin64
2). Bad way, but quickly: 
Drop the dlls in C:\Windows\System32
Another way: 
Place it into any directory and set MAGIC environment variable with /path/to/libmagic.dll

For x86 Windows:
1). Download dll's from http://gnuwin32.sourceforge.net/packages/file.htm
2). Same for x64.

**Comment by hey-red** [comment]
Also, you need to set MagicFilePath property.
e.x:
`Mime.MagicFilePath = "/path/to/magic.mgc";`

**Comment by monotore** [comment]
I can't find a MagicFile property on Mime. I'm using version 1.1.0 from nuget.

**Comment by hey-red** [comment]
This property added after 1.1.0 release.
I will update package soon.
As temporary solution place it into
$LOCALAPPDATA/.magic/magic.mgc
(not tested).

**Comment by hey-red** [comment]
@monotore Package has been updated.

**Comment by monotore** [comment]
Thanks. Works perfect!

Do you know where to get an updatet magic.mgc file? The one in https://github.com/pidydx/libmagicwin64 is two years old.

**Comment by hey-red** [comment]
From http://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=libmagic1&searchon=names

Download amd64 package and unpack it via 7zip or another archiver.
Magic files located in:
/usr/share/misc/magic
/usr/share/misc/magic.mgc

Also, check libmagic version via Magic.Version property. Newest version of this magic file cannot be supported by your libmagic.dll
I do not remember which version in the repo, but I think 5.2.0.
